### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by rudolfb** [Multiply/iron-router-progress#56]
Hi,

Currently the loading bar is designed for Left-to-Right languages, with the loading bar progress direction left-to-right and the spinner on the right of the screen. Would it be possible to make the direction of the loading bar as well as the position of the spinner configurable so that it would be easier to support Right-to-Left languages?

Regards

Rudolf Bargholz

**Comment by Multiply** [comment]
Yes. This can be completed solely with CSS or LESS tho.

``` css
#iron-router-progress { left: auto; right: 0; }
#iron-router-progress.spinner:before { right: auto; left: 10px; }
```

Try that, I haven't tested it, but it should do the trick :)
